Repository opencad-community/opencad, pull requests merged in 2023-02, with the labels that each got.

#6 Importing en.inc.php from Legacy OC
  core/locale/en.inc.php
Labels: enhancement

#9 Creation of public files; additions of login pages and registration pages; home
  assets/images/favicon.ico
  assets/images/gplv3-127x51.png
  assets/images/icon.png
  assets/images/logo.png
  assets/images/templates/actionpage/index.php
  assets/images/templates/actionpage/login.php
  assets/images/templates/actionpage/registration.php
  assets/images/templates/home.php
  assets/images/templates/images/favicon.ico
  assets/images/templates/images/gplv3-127x51.png
  assets/images/templates/images/icon.png
  assets/images/templates/images/logo.png
  assets/images/templates/index.html
  assets/images/templates/index.php
  assets/images/templates/index.txt
  templates/actionpage/index.php
  templates/actionpage/login.php
  templates/actionpage/registration.php
  templates/home.php
  templates/images/favicon.ico
  templates/images/gplv3-127x51.png
  templates/images/icon.png
  templates/images/logo.png
  templates/images/templates/actionpage/index.php
  templates/images/templates/actionpage/login.php
  templates/images/templates/actionpage/registration.php
  templates/images/templates/home.php
  templates/images/templates/images/favicon.ico
  templates/images/templates/images/gplv3-127x51.png
  templates/images/templates/images/icon.png
  templates/images/templates/images/logo.png
  templates/images/templates/index.html
  templates/images/templates/index.php
  templates/images/templates/index.txt
  templates/index.php
Labels: enhancement, help wanted

#12 Issue #10 - Template files // Duplicate files located within directory
  assets/images/templates/actionpage/index.php
  assets/images/templates/actionpage/registration.php
  assets/images/templates/home.php
  assets/images/templates/images/favicon.ico
  assets/images/templates/images/gplv3-127x51.png
  assets/images/templates/images/icon.png
  assets/images/templates/images/logo.png
  assets/images/templates/index.html
  assets/images/templates/index.txt
  core/templates/actionpage/index.php
  core/templates/actionpage/login.php
  core/templates/actionpage/registration.php
  core/templates/home.php
  core/templates/index.html
  core/templates/index.php
  public/index.php
  templates/actionpage/index.php
  templates/actionpage/registration.php
  templates/home.php
  templates/images/favicon.ico
  templates/images/gplv3-127x51.png
  templates/images/icon.png
  templates/images/logo.png
  templates/images/templates/actionpage/index.php
  templates/images/templates/actionpage/login.php
  templates/images/templates/actionpage/registration.php
  templates/images/templates/home.php
  templates/images/templates/images/favicon.ico
  templates/images/templates/images/gplv3-127x51.png
  templates/images/templates/images/icon.png
  templates/images/templates/images/logo.png
  templates/images/templates/index.html
  templates/images/templates/index.txt
Labels: bug, enhancement
